{% set name = "horovod" %}
{% set version = "0.23.0" %}
{% set tf_version = "2.7" %}
{% if cuda_compiler_version == "None" %}
{% set tf_variant = "cpu" %}

{% else %}
{% set tf_variant = "cuda" %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/horovod/horovod
  git_rev: v{{ version }}
  patches:
    - 0001-disable-XLA.patch

build:
  number: 0
  script_env:
    - HOROVOD_CUDA_HOME=/usr/local/cuda  # [cuda_compiler_version != 'None']
    - HOROVOD_NCCL_HOME=$PREFIX  # [cuda_compiler_version != 'None']
    - HOROVOD_GPU_OPERATIONS=NCCL  # [cuda_compiler_version != 'None']
    - HOROVOD_NCCL_LINK=SHARED  # [cuda_compiler_version != 'None']
    - HOROVOD_WITH_TENSORFLOW=1
    - HOROVOD_WITHOUT_PYTORCH=1
    - HOROVOD_WITHOUT_MXNET=1
    - HOROVOD_WITH_MPI=1
  script:
    - "{{ PYTHON }} -m pip install . -vv"  # [unix]
  skip: true  # [osx and cuda_compiler_version != 'None']
  skip: true  # [ppc64le and cuda_compiler_version == 'None']
  skip: true  # [not linux]
  skip: true  # [ppc64le]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != 'None']
    - cmake  >=3.7
    - make  # [unix]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]

  host:
    - python
    - pip
    - wheel
    - pyyaml
    - cloudpickle
    - psutil
    - nccl  # [cuda_compiler_version != 'None']
    - mpich
    - mpi4py
    - tensorflow {{ tf_version }}.* {{ tf_variant }}*

  run:
    - python
    - pyyaml
    - cloudpickle
    - psutil
    - nccl  # [cuda_compiler_version != 'None']
    - {{ pin_compatible('mpich') }}
    - mpi4py
    - tensorflow {{ tf_version }}.* {{ tf_variant }}*
    - tensorflow-estimator
    - __cuda  # [cuda_compiler_version != "None"]


test:
  imports:
    - horovod
    - horovod.tensorflow

about:
  home: https://github.com/horovod/horovod
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Distributed training framework for TensorFlow, Keras, PyTorch, and Apache MXNet.'
  doc_url: https://github.com/horovod/horovod
  dev_url: https://github.com/horovod/horovod

extra:
  recipe-maintainers:
    - njzjz
